//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing.Unit {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Testing.Unit.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;response xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XML-Schema-instance&quot; version=&quot;1.2&quot; xsi:noNamespaceSchemaLocation=&quot;http://aviationweather.gov/adds/schema/metar1_2.xsd&quot;&gt;
        ///	&lt;request_index&gt;15918721&lt;/request_index&gt;
        ///	&lt;data_source name=&quot;metars&quot; /&gt;
        ///	&lt;request type=&quot;retrieve&quot; /&gt;
        ///	&lt;errors /&gt;
        ///	&lt;warnings /&gt;
        ///	&lt;time_taken_ms&gt;3&lt;/time_taken_ms&gt;
        ///	&lt;data num_results=&quot;3&quot;&gt;
        ///		&lt;METAR&gt;
        ///			&lt;raw_text&gt;KATL 192352Z 04017KT 8SM -RA BKN007 OVC012 13/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KATL_SPECI_METARs_XML {
            get {
                return ResourceManager.GetString("KATL_SPECI_METARs_XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No errors
        ///No warnings
        ///4 ms
        ///data source=stations
        ///3 results
        ///station_id, wmo_id, latitude, longitude, elevation_m, site, state, country, site_type
        ///KDEN,72565,39.85,-104.65,1640.0,DENVER(DIA)    ,CO,US,METAR TAF
        ///KSEA,72793,47.45,-122.32,136.0,SEATTLE/METRO   ,WA,US,METAR TAF
        ///PHNL,91182,21.33,-157.92,4.0,HONOLULU        ,HI,US,METAR TAF;.
        /// </summary>
        internal static string KDEN_KSEA_PHNL_StationInfo_CSV {
            get {
                return ResourceManager.GetString("KDEN_KSEA_PHNL_StationInfo_CSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No errors
        ///No warnings
        ///3 ms
        ///data source= metars
        ///2 results
        ///raw_text, station_id, observation_time, latitude, longitude, temp_c, dewpoint_c, wind_dir_degrees, wind_speed_kt, wind_gust_kt, visibility_statute_mi, altim_in_hg, sea_level_pressure_mb, corrected, auto, auto_station, maintenance_indicator_on, no_signal, lightning_sensor_off, freezing_rain_sensor_off, present_weather_sensor_off, wx_string, sky_cover, cloud_base_ft_agl, sky_cover, cloud_base_ft_agl, sky_cover, cloud_base_ft_agl, sky_cover, cloud_b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KDEN_METAR_CSV {
            get {
                return ResourceManager.GetString("KDEN_METAR_CSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;response xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XML-Schema-instance&quot; version=&quot;1.2&quot; xsi:noNamespaceSchemaLocation=&quot;http://aviationweather.gov/adds/schema/metar1_2.xsd&quot;&gt;
        ///  &lt;request_index&gt;93584933&lt;/request_index&gt;
        ///  &lt;data_source name=&quot;metars&quot; /&gt;
        ///  &lt;request type=&quot;retrieve&quot; /&gt;
        ///  &lt;errors /&gt;
        ///  &lt;warnings /&gt;
        ///  &lt;time_taken_ms&gt;20&lt;/time_taken_ms&gt;
        ///  &lt;data num_results=&quot;25&quot;&gt;
        ///    &lt;METAR&gt;
        ///      &lt;raw_text&gt;KIAD 010107Z 08009KT 8SM18 OVC04 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KIAD_METAR_History {
            get {
                return ResourceManager.GetString("KIAD_METAR_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;response xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XML-Schema-instance&quot; version=&quot;1.2&quot; xsi:noNamespaceSchemaLocation=&quot;http://aviationweather.gov/adds/schema/metar1_2.xsd&quot;&gt;
        ///	&lt;request_index&gt;15836447&lt;/request_index&gt;
        ///	&lt;data_source name = &quot;metars&quot; /&gt;
        ///	&lt;request type=&quot;retrieve&quot; /&gt;
        ///	&lt;errors /&gt;
        ///	&lt;warnings /&gt;
        ///	&lt;time_taken_ms&gt;4&lt;/time_taken_ms&gt;
        ///	&lt;data num_results = &quot;2&quot; &gt;
        ///		&lt;METAR&gt;
        ///			&lt;raw_text&gt;KIAD 192252Z 15003KT 10SM FEW120 SCT180 B [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KIAD_METAR_XML {
            get {
                return ResourceManager.GetString("KIAD_METAR_XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;response xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XML-Schema-instance&quot; version=&quot;1.0&quot; xsi:noNamespaceSchemaLocation=&quot;http://weather.aero/schema/station1_0.xsd&quot;&gt;
        ///	&lt;request_index&gt;7850904&lt;/request_index&gt;
        ///	&lt;data_source name=&quot;stations&quot;/&gt;
        ///	&lt;request type=&quot;retrieve&quot;/&gt;
        ///	&lt;errors/&gt;
        ///	&lt;warnings/&gt;
        ///	&lt;time_taken_ms&gt;4&lt;/time_taken_ms&gt;
        ///	&lt;data num_results=&quot;3&quot;&gt;
        ///		&lt;Station&gt;
        ///			&lt;station_id&gt;KIAD&lt;/station_id&gt;
        ///			&lt;wmo_id&gt;72403&lt;/wmo_id&gt;
        ///			&lt;latitude&gt;38.93&lt;/latitude&gt;
        ///			&lt;longitude&gt;-77. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KIAD_ORBB_ZBAA_StationInfo_XML {
            get {
                return ResourceManager.GetString("KIAD_ORBB_ZBAA_StationInfo_XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;response xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XML-Schema-instance&quot; version=&quot;1.2&quot; xsi:noNamespaceSchemaLocation=&quot;http://aviationweather.gov/adds/schema/taf1_2.xsd&quot;&gt;
        ///	&lt;request_index&gt;45901764&lt;/request_index&gt;
        ///	&lt;data_source name=&quot;tafs&quot; /&gt;
        ///	&lt;request type=&quot;retrieve&quot; /&gt;
        ///	&lt;errors /&gt;
        ///	&lt;warnings /&gt;
        ///	&lt;time_taken_ms&gt;11&lt;/time_taken_ms&gt;
        ///	&lt;data num_results=&quot;4&quot;&gt;
        ///		&lt;TAF&gt;
        ///			&lt;raw_text&gt;TAF AMD KMUI 042359Z 0423/0601 18012KT 9999 FEW140  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KMUI_TAF_XML {
            get {
                return ResourceManager.GetString("KMUI_TAF_XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;response xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XML-Schema-instance&quot; version=&quot;1.2&quot; xsi:noNamespaceSchemaLocation=&quot;http://aviationweather.gov/adds/schema/taf1_2.xsd&quot;&gt;
        ///	&lt;request_index&gt;69296481&lt;/request_index&gt;
        ///	&lt;data_source name=&quot;tafs&quot;/&gt;
        ///	&lt;request type=&quot;retrieve&quot;/&gt;
        ///	&lt;errors/&gt;
        ///	&lt;warnings/&gt;
        ///	&lt;time_taken_ms&gt;9&lt;/time_taken_ms&gt;
        ///	&lt;data num_results=&quot;11&quot;&gt;
        ///		&lt;TAF&gt;
        ///			&lt;raw_text&gt;KPHL 262320Z 2700/2806 11008KT P6SM SCT040 BKN100 FM270800 10010KT P6SM BKN020 OVC040 FM271000  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KPHL_TAF_XML {
            get {
                return ResourceManager.GetString("KPHL_TAF_XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No errors
        ///No warnings
        ///10 ms
        ///data source=tafs
        ///7 results
        ///raw_text,station_id,issue_time,bulletin_time,valid_time_from,valid_time_to,remarks,latitude,longitude,elevation_m,fcst_time_from,fcst_time_to,change_indicator,time_becoming,probability,wind_dir_degrees,wind_speed_kt,wind_gust_kt,wind_shear_hgt_ft_agl,wind_shear_dir_degrees,wind_shear_speed_kt,visibility_statute_mi,altim_in_hg,vert_vis_ft,wx_string,not_decoded,sky_cover,cloud_base_ft_agl,cloud_type,sky_cover,cloud_base_ft_agl,cloud_type,sky_cover,cloud_b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KTCC_TAF_WindSheer_CSV {
            get {
                return ResourceManager.GetString("KTCC_TAF_WindSheer_CSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;response xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XML-Schema-instance&quot; version=&quot;1.2&quot; xsi:noNamespaceSchemaLocation=&quot;http://aviationweather.gov/adds/schema/taf1_2.xsd&quot;&gt;
        ///  &lt;request_index&gt;640369&lt;/request_index&gt;
        ///  &lt;data_source name=&quot;tafs&quot; /&gt;
        ///  &lt;request type=&quot;retrieve&quot; /&gt;
        ///  &lt;errors /&gt;
        ///  &lt;warnings /&gt;
        ///  &lt;time_taken_ms&gt;19&lt;/time_taken_ms&gt;
        ///  &lt;data num_results=&quot;7&quot;&gt;
        ///    &lt;TAF&gt;
        ///      &lt;raw_text&gt;KTCC 140005Z 1400/1424 33012KT P6SM SKC W [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KTCC_TAF_WindSheer_XML {
            get {
                return ResourceManager.GetString("KTCC_TAF_WindSheer_XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No errors
        ///No warnings
        ///19 ms
        ///data source=tafs
        ///9 results
        ///raw_text,station_id,issue_time,bulletin_time,valid_time_from,valid_time_to,remarks,latitude,longitude,elevation_m,fcst_time_from,fcst_time_to,change_indicator,time_becoming,probability,wind_dir_degrees,wind_speed_kt,wind_gust_kt,wind_shear_hgt_ft_agl,wind_shear_dir_degrees,wind_shear_speed_kt,visibility_statute_mi,altim_in_hg,vert_vis_ft,wx_string,not_decoded,sky_cover,cloud_base_ft_agl,cloud_type,sky_cover,cloud_base_ft_agl,cloud_type,sky_cover,cloud_b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PASY_Icing_Turbulence_TAF_CSV {
            get {
                return ResourceManager.GetString("PASY_Icing_Turbulence_TAF_CSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;response xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XML-Schema-instance&quot; version=&quot;1.2&quot; xsi:noNamespaceSchemaLocation=&quot;http://aviationweather.gov/adds/schema/taf1_2.xsd&quot;&gt;
        ///  &lt;request_index&gt;28165578&lt;/request_index&gt;
        ///  &lt;data_source name=&quot;tafs&quot; /&gt;
        ///  &lt;request type=&quot;retrieve&quot; /&gt;
        ///  &lt;errors /&gt;
        ///  &lt;warnings /&gt;
        ///  &lt;time_taken_ms&gt;24&lt;/time_taken_ms&gt;
        ///  &lt;data num_results=&quot;9&quot;&gt;
        ///    &lt;TAF&gt;
        ///      &lt;raw_text&gt;TAF AMD PASY 132330Z 1323/1504 35025G35 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PASY_Icing_Turbulence_TAF_XML {
            get {
                return ResourceManager.GetString("PASY_Icing_Turbulence_TAF_XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No errors
        ///No warnings
        ///41 ms
        ///data source=tafs
        ///31 results
        ///raw_text,station_id,issue_time,bulletin_time,valid_time_from,valid_time_to,remarks,latitude,longitude,elevation_m,fcst_time_from,fcst_time_to,change_indicator,time_becoming,probability,wind_dir_degrees,wind_speed_kt,wind_gust_kt,wind_shear_hgt_ft_agl,wind_shear_dir_degrees,wind_shear_speed_kt,visibility_statute_mi,altim_in_hg,vert_vis_ft,wx_string,not_decoded,sky_cover,cloud_base_ft_agl,cloud_type,sky_cover,cloud_base_ft_agl,cloud_type,sky_cover,c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PHNL_KSEA_KDEN_TAF_CSV {
            get {
                return ResourceManager.GetString("PHNL_KSEA_KDEN_TAF_CSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;response xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XML-Schema-instance&quot; version=&quot;1.2&quot; xsi:noNamespaceSchemaLocation=&quot;http://aviationweather.gov/adds/schema/metar1_2.xsd&quot;&gt;
        ///  &lt;request_index&gt;83098098&lt;/request_index&gt;
        ///  &lt;data_source name=&quot;metars&quot; /&gt;
        ///  &lt;request type=&quot;retrieve&quot; /&gt;
        ///  &lt;errors /&gt;
        ///  &lt;warnings /&gt;
        ///  &lt;time_taken_ms&gt;7&lt;/time_taken_ms&gt;
        ///  &lt;data num_results=&quot;1&quot;&gt;
        ///    &lt;METAR&gt;
        ///      &lt;raw_text&gt;WALL 092200Z 31004KT 9000 FEW018 2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WALL_NoQualityControlFlags_METAR {
            get {
                return ResourceManager.GetString("WALL_NoQualityControlFlags_METAR", resourceCulture);
            }
        }
    }
}
